version: 2

references:
  python_node_image: &python_node_image
    docker:
      - image: circleci/python:3.6.5-node

  python_node_postgres_images: &python_node_postgres_images
    docker:
      - image: circleci/python:3.6.5-node
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: test_notification_api

  deploy_image: &deploy_image
    docker:
      - image: circleci/python:3.6.5-node

  undeploy_image: &undeploy_image
    docker:
      - image: circleci/python:3.7-node

  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

  cf_install: &cf_install
    run:
      command: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
        mkdir -p `pwd`/bin
        chmod +x ./cf
        mv ./cf bin/
        echo export PATH="$PWD/bin:\$PATH" >> $BASH_ENV
        source $BASH_ENV
        cf install-plugin -f https://github.com/contraband/autopilot/releases/download/0.0.6/autopilot-linux

  cf_login: &cf_login
    run:
      command: make cf-login

  cf_login_prod: &cf_login_prod
    run:
      command: make cf-login-prod

  master_branch: &master_branch
    filters:
      branches:
        only:
          - master

  not_master_branch: &not_master_branch
    filters:
      branches:
        ignore:
          - master

jobs:
  setup:
    <<: *python_node_image
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - Makefile
            - utils
            - api
            - admin
            - status
            - ci

  build-admin:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make admin.setup
      - run: make admin.vendor
      - persist_to_workspace:
          root: .
          paths:
            - admin

  test-admin:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make admin.setup-dev
      - run: echo 're-enable tests here'
      - run: echo 'make admin.test'

  test-api:
    <<: *python_node_postgres_images
    steps:
      - *attach_workspace
      - run: make api.setup-dev
      - run: make -C api test-accept_invite
      - run: make -C api test-authentication
      - run: make -C api test-aws
      - run: make -C api test-commands
      - run: make -C api test-dvla_organisation
      - run: make -C api test-email_branding
      - run: make -C api test-events
      - run: make -C api test-inbound_number
      - run: make -C api test-inbound_sms
      - run: make -C api test-invite
      - run: make -C api test-job
      - run: make -C api test-notifications
      - run: make -C api test-organisation
      - run: make -C api test-performance_platform
      - run: make -C api test-roots
      - run: make -C api test-template
      - run: make -C api test-template_statistics
      - run: make -C api test-user
      - run: make -C api test-letters
      - run: make -C api test-provider_details
      - run: make -C api test-public_contracts

  build-api:
    <<: *python_node_image
    steps:
      - *attach_workspace
      - run: make api.setup
      - run: make api.vendor
      - persist_to_workspace:
          root: .
          paths:
            - api

  cleanup-old-deploys:
    <<: *undeploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make -C ci undeploy-feature-branches

  deploy-dev-admin:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make admin.deploy-dev

  deploy-dev-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make create-service-psql
      - run: make api.deploy-dev

  deploy-dev-celery:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login
      - run: make create-service-psql
      - run: make api.deploy-dev-celery

  deploy-prod-admin:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make admin.deploy

  deploy-prod-api:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make api.deploy

  deploy-prod-celery:
    <<: *deploy_image
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make api.deploy-celery

  deploy-statuspage:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - *cf_install
      - *attach_workspace
      - *cf_login_prod
      - run: make status.deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup
      - build-admin:
          requires:
            - setup

      - build-api:
          requires:
            - setup

      - test-admin:
          requires:
            - setup

      - test-api:
          requires:
            - setup

      - deploy-dev-admin:
          requires:
            - build-admin

      - deploy-dev-api:
          requires:
            - build-api

      - deploy-dev-celery:
          requires:
            - build-api

      - cleanup-old-deploys:
          requires:
            - setup

      - unlock-prod-deploy:
          <<: *master_branch
          type: approval
          requires:
            - deploy-dev-admin
            - test-api
            - test-admin
            - deploy-dev-api
            - deploy-dev-celery

      - deploy-prod-admin:
          <<: *master_branch
          requires:
            - unlock-prod-deploy

      - deploy-prod-api:
          <<: *master_branch
          requires:
            - unlock-prod-deploy

      - deploy-prod-celery:
          <<: *master_branch
          requires:
            - unlock-prod-deploy

      - deploy-statuspage:
          <<: *master_branch
          requires:
            - unlock-prod-deploy
